/**
 * Theme presets — pre-baked light/dark color sets selectable from the
 * Payload admin via the ThemePresetSelector card grid.
 *
 * Token names match the shadcn/ui semantic tokens defined in
 * `src/globals/Theme.ts` so the selector can write preset values into the
 * form verbatim. Keep this list in sync with the field list in Theme.ts
 * (the SEMANTIC_TOKENS tuple below is the single source of truth).
 */

export const SEMANTIC_TOKENS = [
  "background",
  "foreground",
  "card",
  "cardForeground",
  "popover",
  "popoverForeground",
  "primary",
  "primaryForeground",
  "secondary",
  "secondaryForeground",
  "muted",
  "mutedForeground",
  "accent",
  "accentForeground",
  "destructive",
  "destructiveForeground",
  "border",
  "input",
  "ring",
] as const;

export type SemanticToken = (typeof SEMANTIC_TOKENS)[number];

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  /** Radius in px, applied to Tailwind's --radius token. */
  radius: number;
  light: Record<SemanticToken, string>;
  dark: Record<SemanticToken, string>;
}

/**
 * Curated presets. Light/dark surfaces are tuned per-preset rather than
 * auto-derived — preset identity comes from the accent, not a washed palette.
 */
export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "simal-brand",
    name: "Simal Brand",
    description: "Default pink-forward brand palette.",
    radius: 8,
    light: {
      background: "#FFFFFF",
      foreground: "#0F172A",
      card: "#FFFFFF",
      cardForeground: "#0F172A",
      popover: "#FFFFFF",
      popoverForeground: "#0F172A",
      primary: "#DF4C73",
      primaryForeground: "#FFFFFF",
      secondary: "#F1F5F9",
      secondaryForeground: "#0F172A",
      muted: "#F1F5F9",
      mutedForeground: "#6B7280",
      accent: "#F1F5F9",
      accentForeground: "#0F172A",
      destructive: "#DC2626",
      destructiveForeground: "#FFFFFF",
      border: "#E5E7EB",
      input: "#E5E7EB",
      ring: "#DF4C73",
    },
    dark: {
      background: "#0B1120",
      foreground: "#F8FAFC",
      card: "#111827",
      cardForeground: "#F8FAFC",
      popover: "#111827",
      popoverForeground: "#F8FAFC",
      primary: "#DF4C73",
      primaryForeground: "#FFFFFF",
      secondary: "#1F2937",
      secondaryForeground: "#F8FAFC",
      muted: "#1F2937",
      mutedForeground: "#94A3B8",
      accent: "#1F2937",
      accentForeground: "#F8FAFC",
      destructive: "#DC2626",
      destructiveForeground: "#FFFFFF",
      border: "#1F2937",
      input: "#1F2937",
      ring: "#DF4C73",
    },
  },
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    description: "Trust-first blue. Cool and corporate.",
    radius: 10,
    light: {
      background: "#FFFFFF",
      foreground: "#0B1F3A",
      card: "#FFFFFF",
      cardForeground: "#0B1F3A",
      popover: "#FFFFFF",
      popoverForeground: "#0B1F3A",
      primary: "#286FB4",
      primaryForeground: "#FFFFFF",
      secondary: "#EFF6FB",
      secondaryForeground: "#0B1F3A",
      muted: "#EFF6FB",
      mutedForeground: "#5B708B",
      accent: "#B0DDE4",
      accentForeground: "#0B1F3A",
      destructive: "#DC2626",
      destructiveForeground: "#FFFFFF",
      border: "#DCE7F1",
      input: "#DCE7F1",
      ring: "#286FB4",
    },
    dark: {
      background: "#0A1628",
      foreground: "#EAF2FA",
      card: "#0F1E36",
      cardForeground: "#EAF2FA",
      popover: "#0F1E36",
      popoverForeground: "#EAF2FA",
      primary: "#5BA4E0",
      primaryForeground: "#061222",
      secondary: "#13233D",
      secondaryForeground: "#EAF2FA",
      muted: "#13233D",
      mutedForeground: "#9DB3CC",
      accent: "#1B3458",
      accentForeground: "#EAF2FA",
      destructive: "#F87171",
      destructiveForeground: "#1A0606",
      border: "#1B2D4A",
      input: "#1B2D4A",
      ring: "#5BA4E0",
    },
  },
  {
    id: "forest-green",
    name: "Forest Green",
    description: "Grounded and natural. Reads sustainable.",
    radius: 6,
    light: {
      background: "#FBFCFB",
      foreground: "#14241B",
      card: "#FFFFFF",
      cardForeground: "#14241B",
      popover: "#FFFFFF",
      popoverForeground: "#14241B",
      primary: "#16A34A",
      primaryForeground: "#FFFFFF",
      secondary: "#ECF4EE",
      secondaryForeground: "#14241B",
      muted: "#ECF4EE",
      mutedForeground: "#5A6E63",
      accent: "#D7EAD9",
      accentForeground: "#14241B",
      destructive: "#B91C1C",
      destructiveForeground: "#FFFFFF",
      border: "#DDE6DF",
      input: "#DDE6DF",
      ring: "#16A34A",
    },
    dark: {
      background: "#0B1410",
      foreground: "#EAF2EC",
      card: "#111C16",
      cardForeground: "#EAF2EC",
      popover: "#111C16",
      popoverForeground: "#EAF2EC",
      primary: "#34D17C",
      primaryForeground: "#04140B",
      secondary: "#16241B",
      secondaryForeground: "#EAF2EC",
      muted: "#16241B",
      mutedForeground: "#9BB1A2",
      accent: "#1C3326",
      accentForeground: "#EAF2EC",
      destructive: "#F87171",
      destructiveForeground: "#1A0606",
      border: "#1B2D22",
      input: "#1B2D22",
      ring: "#34D17C",
    },
  },
  {
    id: "sunset-orange",
    name: "Sunset Orange",
    description: "Warm and energetic. Strong CTA pop.",
    radius: 12,
    light: {
      background: "#FFFBF7",
      foreground: "#2B1A0E",
      card: "#FFFFFF",
      cardForeground: "#2B1A0E",
      popover: "#FFFFFF",
      popoverForeground: "#2B1A0E",
      primary: "#EA580C",
      primaryForeground: "#FFFFFF",
      secondary: "#FEEEE0",
      secondaryForeground: "#2B1A0E",
      muted: "#FEEEE0",
      mutedForeground: "#74573E",
      accent: "#FDD9B5",
      accentForeground: "#2B1A0E",
      destructive: "#B91C1C",
      destructiveForeground: "#FFFFFF",
      border: "#F3DCC4",
      input: "#F3DCC4",
      ring: "#EA580C",
    },
    dark: {
      background: "#181009",
      foreground: "#FBEFE0",
      card: "#22160C",
      cardForeground: "#FBEFE0",
      popover: "#22160C",
      popoverForeground: "#FBEFE0",
      primary: "#FB8B3C",
      primaryForeground: "#1F1003",
      secondary: "#2D1E12",
      secondaryForeground: "#FBEFE0",
      muted: "#2D1E12",
      mutedForeground: "#C7A486",
      accent: "#3A2415",
      accentForeground: "#FBEFE0",
      destructive: "#F87171",
      destructiveForeground: "#1A0606",
      border: "#2E2014",
      input: "#2E2014",
      ring: "#FB8B3C",
    },
  },
  {
    id: "royal-purple",
    name: "Royal Purple",
    description: "Premium and editorial.",
    radius: 8,
    light: {
      background: "#FFFFFF",
      foreground: "#1E1330",
      card: "#FFFFFF",
      cardForeground: "#1E1330",
      popover: "#FFFFFF",
      popoverForeground: "#1E1330",
      primary: "#7C3AED",
      primaryForeground: "#FFFFFF",
      secondary: "#F1ECFA",
      secondaryForeground: "#1E1330",
      muted: "#F1ECFA",
      mutedForeground: "#5E4F7A",
      accent: "#DDD0F4",
      accentForeground: "#1E1330",
      destructive: "#B91C1C",
      destructiveForeground: "#FFFFFF",
      border: "#E0D6EE",
      input: "#E0D6EE",
      ring: "#7C3AED",
    },
    dark: {
      background: "#100823",
      foreground: "#EFE7FA",
      card: "#180E32",
      cardForeground: "#EFE7FA",
      popover: "#180E32",
      popoverForeground: "#EFE7FA",
      primary: "#A678F5",
      primaryForeground: "#0E0420",
      secondary: "#1F1338",
      secondaryForeground: "#EFE7FA",
      muted: "#1F1338",
      mutedForeground: "#A89BC4",
      accent: "#2A1B4D",
      accentForeground: "#EFE7FA",
      destructive: "#F87171",
      destructiveForeground: "#1A0606",
      border: "#221642",
      input: "#221642",
      ring: "#A678F5",
    },
  },
  {
    id: "midnight-slate",
    name: "Midnight Slate",
    description: "Neutral and restrained. Enterprise IT.",
    radius: 4,
    light: {
      background: "#FFFFFF",
      foreground: "#0F172A",
      card: "#FFFFFF",
      cardForeground: "#0F172A",
      popover: "#FFFFFF",
      popoverForeground: "#0F172A",
      primary: "#475569",
      primaryForeground: "#FFFFFF",
      secondary: "#F1F5F9",
      secondaryForeground: "#0F172A",
      muted: "#F1F5F9",
      mutedForeground: "#64748B",
      accent: "#E2E8F0",
      accentForeground: "#0F172A",
      destructive: "#DC2626",
      destructiveForeground: "#FFFFFF",
      border: "#E2E8F0",
      input: "#E2E8F0",
      ring: "#475569",
    },
    dark: {
      background: "#0B0F1A",
      foreground: "#E5EAF2",
      card: "#111726",
      cardForeground: "#E5EAF2",
      popover: "#111726",
      popoverForeground: "#E5EAF2",
      primary: "#9AA8BC",
      primaryForeground: "#0B0F1A",
      secondary: "#1A2235",
      secondaryForeground: "#E5EAF2",
      muted: "#1A2235",
      mutedForeground: "#94A3B8",
      accent: "#1F2A40",
      accentForeground: "#E5EAF2",
      destructive: "#F87171",
      destructiveForeground: "#1A0606",
      border: "#1F2A40",
      input: "#1F2A40",
      ring: "#9AA8BC",
    },
  },
];

export const DEFAULT_PRESET_ID = "simal-brand";

export function getPreset(id: string | undefined | null): ThemePreset | undefined {
  if (!id) return undefined;
  return THEME_PRESETS.find((p) => p.id === id);
}
